window.SERVICES = [
  { name: "Job Consulting", keyword: "professional,career", category: "Jobs", desc: "Expert guidance for your dream career path." },
  { name: "Passport & Visa Service", keyword: "visa,ducument", category: "Travel", desc: "Hassle-free passport and visa processing." },
  { name: "Tour Packages", keyword: "travel,tourism", category: "Travel", desc: "Curated tours and travel packages worldwide." },
  { name: "Hotel Booking", keyword: "hotel,room", category: "Hotels", desc: "Best deals on hotels across the globe." },
  { name: "Train Booking", keyword: "train,railway", category: "Travel", desc: "Easy train ticket reservations made simple." },
  { name: "Flight Booking", keyword: "airplane,flight", category: "Travel", desc: "Compare and book flights at unbeatable rates." },
  { name: "Bus Booking", keyword: "bus,transport", category: "Travel", desc: "Reserve comfortable bus seats in seconds." },
  { name: "Real Estate", keyword: "realestate,house", category: "Real Estate", desc: "Find your perfect home or investment property." },
  { name: "Ambulance Service", keyword: "ambulance,emergency", category: "Health", desc: "24x7 emergency ambulance dispatch." },
  { name: "Doctor on Video Call", keyword: "doctor,telemedicine", category: "Health", desc: "Consult certified doctors from home." },
  { name: "Cab Service", keyword: "taxi,cab", category: "Automotive", desc: "Reliable city cabs and outstation rides." },
  { name: "Banquet Hall", keyword: "banquet,wedding+hall", category: "Events", desc: "Premium banquet halls for every occasion." },
  { name: "Personal Loan", keyword: "loan,finance", category: "Financial", desc: "Quick personal loans with low interest rates." },
  { name: "Business Loan", keyword: "business,finance", category: "Financial", desc: "Fuel your business growth with easy loans." },
  { name: "Vehicle Loan", keyword: "car,loan", category: "Financial", desc: "Drive home your dream vehicle today." },
  { name: "CSC Center", keyword: "csc,center", category: "Financial", desc: "All government services under one roof." },
  { name: "Home Appliances", keyword: "appliances,kitchen", category: "Home", desc: "Top brand appliances delivered to your door." },
  { name: "Mobiles", keyword: "smartphone,mobile", category: "Tech", desc: "Latest smartphones at competitive prices." },
  { name: "Desktop Computer", keyword: "desktop,computer", category: "Tech", desc: "Powerful desktops for work and play." },
  { name: "Laptops", keyword: "laptop,computer", category: "Tech", desc: "Wide range of laptops for every budget." },
  { name: "Hardware", keyword: "hardware,tools", category: "Tech", desc: "Quality computer hardware and accessories." },
  { name: "Sanitary Ware", keyword: "bathroom,sanitary", category: "Home", desc: "Modern sanitary ware for stylish bathrooms." },
  { name: "Plumbing", keyword: "plumber,pipe", category: "Home Services", desc: "Trusted plumbers for repairs and fittings." },
  { name: "Electrician", keyword: "electrician,electric", category: "Home Services", desc: "Skilled electricians for all electrical work." },
  { name: "Carpenter", keyword: "carpenter,wood", category: "Home Services", desc: "Expert carpenters for furniture and repairs." },
  { name: "Painting", keyword: "painting,wall", category: "Home Services", desc: "Transform your walls with pro painters." },
  { name: "AC Repair", keyword: "aircon,repair", category: "Home Services", desc: "Fast AC servicing and repair at home." },
  { name: "Home Cleaning", keyword: "cleaning,home", category: "Home Services", desc: "Professional home cleaning services." },
  { name: "Deep Cleaning", keyword: "deepcleaning,housekeeping", category: "Home Services", desc: "Thorough deep cleaning for sparkling homes." },
  { name: "Pest Control", keyword: "pestcontrol,insect", category: "Home Services", desc: "Safe and effective pest control treatments." },
  { name: "Laundry", keyword: "laundry,washing", category: "Home Services", desc: "Pickup and delivery laundry services." },
  { name: "Web Design", keyword: "webdesign,coding", category: "Tech", desc: "Beautiful, conversion-focused websites." },
  { name: "App Development", keyword: "appdevelopment,mobile", category: "Tech", desc: "Custom mobile apps for iOS and Android." },
  { name: "Digital Marketing", keyword: "digitalmarketing,social", category: "Tech", desc: "Grow your brand online with proven strategies." },
  { name: "SEO", keyword: "seo,search", category: "Tech", desc: "Rank higher on Google with expert SEO." },
  { name: "Social Media Marketing", keyword: "socialmedia,marketing", category: "Tech", desc: "Engage audiences across all social channels." },
  { name: "Content Writing", keyword: "writing,content", category: "Tech", desc: "Compelling content that converts readers." },
  { name: "Graphic Design", keyword: "graphicdesign,creative", category: "Tech", desc: "Eye-catching designs for your brand." },
  { name: "Photography", keyword: "photography,camera", category: "Events", desc: "Professional photographers for every moment." },
  { name: "Videography", keyword: "videography,filming", category: "Events", desc: "Cinematic videos for events and brands." },
  { name: "Catering", keyword: "catering,food", category: "Events", desc: "Delicious catering for any size gathering." },
  { name: "Event Planning", keyword: "event,planning", category: "Events", desc: "End-to-end event management services." },
  { name: "Wedding Planning", keyword: "wedding,ceremony", category: "Events", desc: "Plan your dream wedding stress-free." },
  { name: "Interior Design", keyword: "interior,design", category: "Home", desc: "Stunning interiors tailored to your taste." },
  { name: "Moving & Packing", keyword: "moving,boxes", category: "Home Services", desc: "Safe relocation and packing services." },
  { name: "Grocery Delivery", keyword: "grocery,vegetables", category: "Delivery", desc: "Fresh groceries delivered to your doorstep." },
  { name: "Food Delivery", keyword: "food,delivery", category: "Delivery", desc: "Hot meals from your favorite restaurants." },
  { name: "Medicine Delivery", keyword: "medicine,pharmacy", category: "Delivery", desc: "Prescription medicines delivered fast." },
  { name: "Tutoring", keyword: "tutoring,study", category: "Education", desc: "Personalized tutoring for all subjects." },
  { name: "Music Lessons", keyword: "music,guitar", category: "Education", desc: "Learn instruments from expert teachers." },
  { name: "Yoga & Fitness", keyword: "yoga,fitness", category: "Health", desc: "Stay fit with certified yoga trainers." },
  { name: "Beauty & Salon", keyword: "salon,beauty", category: "Beauty", desc: "Salon services in the comfort of your home." },
  { name: "Spa & Massage", keyword: "spa,massage", category: "Beauty", desc: "Relaxing spa and therapeutic massages." },
  { name: "Car Wash", keyword: "carwash,car", category: "Automotive", desc: "Sparkling clean cars at your location." },
  { name: "Car Repair", keyword: "carrepair,mechanic", category: "Automotive", desc: "Expert mechanics for all car issues." },
  { name: "Legal Services", keyword: "legal,lawyer", category: "Legal", desc: "Trusted lawyers for legal advice." },
  { name: "Accounting", keyword: "accounting,finance", category: "Legal", desc: "Reliable accounting and bookkeeping." },
  { name: "Tax Filing", keyword: "tax,filing", category: "Legal", desc: "Maximize savings with expert tax filing." },
  { name: "Insurance", keyword: "insurance,protection", category: "Financial", desc: "Insurance plans for life, health and assets." },
  { name: "Travel Planning", keyword: "travel,planning", category: "Travel", desc: "Custom travel itineraries crafted for you." },
  { name: "Pet Care", keyword: "petcare,dog", category: "Health", desc: "Loving care for your furry friends." },
  { name: "Gardening", keyword: "gardening,plants", category: "Home Services", desc: "Garden design and maintenance experts." },
  { name: "Security Services", keyword: "security,guard", category: "Home Services", desc: "Trained security guards for safety." },
  { name: "Real Estate (Resale)", keyword: "realestate,property", category: "Real Estate", desc: "Resale homes and properties for sale." },
  { name: "CSC Services", keyword: "documents,certificate", category: "Financial", desc: "Apply for government documents easily." }
];

window.CATEGORIES = ["All", "Travel", "Home Services", "Tech", "Financial", "Health", "Events", "Delivery", "Education", "Beauty", "Automotive", "Legal"];
